CFLAGS = -ansi -pedantic -Wall -Werror -Wconversion -Wextra 

TARGET := test

SOURCE := test.c mu_test.h



run: $(TARGET)
	@./$(TARGET)

$(TARGET): $(SOURCE)

clean:
	@rm -f ./$(TARGET) 


.PHONY : clan

